### ISSUE TITLE
Flooding home assistant API with requests

### ISSUE THREAD

**Issue by kegra** [NeoAcheron/midea-ac-py#11]
I am not 100% sure but think this is were all my woes started,
18-12-11 11:57:34 ERROR (MainThread) [hassio.homeassistant] Error on call http://172.30.32.1:8123/api/:
18-12-11 11:57:34 WARNING (MainThread) [hassio.tasks] Watchdog miss API response from Home Assistant

i was trying to trace that error and i see before this error hundreds of lines in the home assistant log about trying to recover from 9999 status and this causes the API to not respond properly , watchdog assumes that api is down and restart hassio

i am on 0.84.2  can you reproduce the problem ?

thank you

**Comment by NeoAcheron** [comment]
Hi there, 

What version of the component are you running?

The prior versions held up the Home Assistant event loop, which made it hang if the component kept retrying. Version 0.1.6 properly hands the call to a separate thread and yields the event loop back to HA.

There is a retry limit in place and will stop if the call doesn't eventually succeed, at which point the flooding should subside. 

Please check the version number in `midea.py` as well as the supporting library files, Home Assistant is pretty bad at keeping the supporting library files up to date, and it had me scratching my head last week. The previous releases were much less stable, and I had crashes every 2 hours due to it.

**Comment by NeoAcheron** [comment]
On another not, 0.84.2 has been rather frustrating, it wiped my lovelace UI config. Luckily I have an automation to make snapshots every night. 

As far as the API flooding, I've not seen it yet since this morning. I'll keep an eye out though, its pretty bad if its crashing HA.

**Comment by kegra** [comment]
yes ! 0.1.6 version eliminated the error ! , i was really frustrated because i haven't correlated the api call crash with your component and i was searching blindly everything , also i could not trace the log since the container was recreated and had no prior logs before the crash (only the supervisor logs) that gave me no clue. After i identified your component as the cause of the error and then tried 0.1.6 version everything seems normal. thank you for your great work.

**Comment by NeoAcheron** [comment]
Ah! Yes, that 9999 error is quite silly. I really don't understand it fully myself. I just know that logging in again does help, which is what the library is doing now in the background. 

Thanks for the great feedback!
